version: 2

presets:
  defaults: &defaults
    working_directory: ~/src
    docker:
      - image: omisegoimages/ewallet-builder:stable
    environment:
      IMAGE_NAME: "omisego/ewallet"

  restore_repo: &restore_repo
    restore_cache:
      name: Restoring repository
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}-
        - v1-repo-

  restore_ewallet_deps: &restore_ewallet_deps
    restore_cache:
      name: Restoring eWallet dependencies from cache
      keys:
        - v1-ewallet-deps-{{ checksum "mix.lock" }}
        - v1-ewallet-deps-

  restore_ewallet_assets_deps: &restore_ewallet_assets_deps
    restore_cache:
      name: Restoring eWallet assets dependencies from cache
      keys:
        - v1-ewallet-assets-deps-{{ checksum "apps/admin_panel/assets/yarn.lock" }}
        - v1-ewallet-assets-deps-

  restore_ewallet_test_build: &restore_ewallet_test_build
    restore_cache:
      name: Restoring eWallet test artifacts from cache
      keys:
        - v1-ewallet-test-build-{{ checksum "mix.exs" }}
        - v1-ewallet-test-build-

  restore_ewallet_prod_build: &restore_ewallet_prod_build
    restore_cache:
      name: Restoring eWallet production artifacts from cache
      keys:
        - v1-ewallet-prod-build-{{ checksum "mix.exs" }}
        - v1-ewallet-prod-build-

  restore_docker_image: &restore_docker_image
    restore_cache:
      name: Restoring Docker image artifacts from cache
      keys:
        - v1-docker-image-{{ checksum "Dockerfile" }}
        - v1-docker-image-

  attach_workspace: &attach_workspace
    attach_workspace:
      name: Attaching workspace
      at: /tmp/workspace

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          name: Saving repository
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  test_ewallet:
    <<: *defaults
    docker:
      - image: omisegoimages/ewallet-builder:stable
      - image: postgres:9.6-alpine
    steps:
      - *restore_repo
      - *restore_ewallet_deps
      - *restore_ewallet_test_build
      - run:
          name: Retrieving eWallet dependencies
          command: |
            # Force rebuilding bcrypt_elixir otherwise it's gonna fail loading NIFs
            find deps/ -name bcrypt_elixir -print0 | xargs -0 rm -rf || true
            make deps-ewallet
      - save_cache:
          name: Caching eWallet dependencies
          key: v1-ewallet-deps-{{ checksum "mix.lock" }}
          paths:
            - deps
      - run:
          name: Building eWallet in test environment
          command: |
            # Force rebuilding bcrypt_elixir otherwise it's gonna fail loading NIFs
            find _build/ -name bcrypt_elixir -print0 | xargs -0 rm -rf || true
            make build-test
      - save_cache:
          name: Caching eWallet test artifacts
          key: v1-ewallet-test-build-{{ checksum "mix.exs" }}
          paths:
            - _build/test
      - run:
          name: Running eWallet tests
          command: |
            for i in $(seq 1 5); do
              echo "Running test (attempt $i/5)"
              if make test-ewallet; then
                break
              fi
            done
          environment:
            DATABASE_URL: postgresql://postgres:@localhost:5432/ewallet
            LOCAL_LEDGER_DATABASE_URL: postgresql://postgres:@localhost:5432/ledger

  test_assets:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_ewallet_assets_deps
      - run:
          name: Retriving eWallet assets dependencies
          command: make deps-assets
      - save_cache:
          name: Caching eWallet assets dependencies
          key: v1-ewallet-assets-deps-{{ checksum "apps/admin_panel/assets/yarn.lock" }}
          paths:
            - apps/admin_panel/assets/node_modules
      - run:
          name: Run assets tests
          command: make test-assets

  build_ewallet:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_ewallet_deps
      - *restore_ewallet_assets_deps
      - *restore_ewallet_prod_build
      - setup_remote_docker
      - run:
          name: Building eWallet in production environment
          command: |
            # Force rebuilding bcrypt_elixir otherwise it's gonna fail loading NIFs
            find deps/ -name bcrypt_elixir -print0 | xargs -0 rm -rf || true
            find _build/ -name bcrypt_elixir -print0 | xargs -0 rm -rf || true
            make build-prod
      - save_cache:
          name: Caching eWallet artifacts
          key: v1-ewallet-prod-build-{{ checksum "mix.exs" }}
          paths:
            - _build/prod/.mix
            - _build/prod/consolidated
            - _build/prod/lib
      - *restore_docker_image
      - run:
          name: Loading Docker image layer cache
          command: |
            docker load -i ~/caches/docker-layers.tar || true
      - run:
          name: Building Docker image
          command: |
            REL_VERSION=$(awk '/version:/ { gsub(/[^0-9a-z\.\-]+/, "", $2); print $2 }' < apps/ewallet/mix.exs)
            mv "_build/prod/rel/ewallet/releases/$REL_VERSION/ewallet.tar.gz" ewallet.tar.gz
            docker build --cache-from "$IMAGE_NAME" -t "$IMAGE_NAME" .
      - run:
          name: Creating Docker image layer cache
          command: |
            mkdir -p ~/caches /tmp/workspace
            docker save -o ~/caches/docker-layers.tar "$IMAGE_NAME"
            cp ~/caches/docker-layers.tar /tmp/workspace/docker-image.tar
      - save_cache:
          name: Saving Docker image layer cache
          paths:
            - ~/caches/docker-layers.tar
          key: v1-docker-image-{{ checksum "Dockerfile" }}
      - persist_to_workspace:
          name: Persisting workspace
          root: /tmp/workspace
          paths:
            - docker-image.tar

  publish_ewallet:
    <<: *defaults
    steps:
      - setup_remote_docker
      - *attach_workspace
      - run:
          name: Publishing Docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker load -i /tmp/workspace/docker-image.tar

            IMAGE_TAG=""

            if [ -n "$CIRCLE_TAG" ]; then
                _ver="${CIRCLE_TAG#*v}"

                # Reduce tags from v1.0.0-pre.1 to 1.0 1.0.0-pre and 1.0.0-pre.1
                while true; do
                    case "$_ver" in
                        *.* ) IMAGE_TAG="$_ver $IMAGE_TAG"; _ver="${_ver%.*}";;
                        * )   break;;
                    esac
                done

                # In case the commit is HEAD of master branch, also tag stable.
                if [ -n "$CIRCLE_REPOSITORY_URL" ] && [ -n "$CIRCLE_SHA1" ]; then
                    _ref="refs/heads/master"
                    _head="$(git ls-remote "$CIRCLE_REPOSITORY_URL" "$_ref" | awk '{ print $1 }')"
                    if [ "$CIRCLE_SHA1" = "$_head" ]; then
                        IMAGE_TAG="stable $IMAGE_TAG"
                    fi
                fi
            elif [ "$CIRCLE_BRANCH" = "master" ]; then
                IMAGE_TAG="dev"
                IMAGE_TAG="dev-$(git rev-parse --short HEAD)"
            fi

            for tag in $IMAGE_TAG; do
                docker tag "$IMAGE_NAME" "$IMAGE_NAME:$tag"
                docker push "$IMAGE_NAME:$tag"
            done

workflows:
  version: 2
  test_build:
    jobs:
      - checkout_code
      - test_ewallet:
          requires:
            - checkout_code
      - test_assets:
          requires:
            - checkout_code
      - build_ewallet:
          requires:
            - test_ewallet
            - test_assets
      - publish_ewallet:
          requires:
            - build_ewallet
